<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-android36.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <SupportedOSPlatformVersion>29.0</SupportedOSPlatformVersion>
    <ApplicationId>com.divintyinteractive.ditunnel</ApplicationId>
    <ApplicationTitle>Di-Tunnel</ApplicationTitle>
    <ApplicationDisplayVersion>$(Version)</ApplicationDisplayVersion>
    <ApplicationVersion>40024</ApplicationVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidStripNativeLibraries>true</AndroidStripNativeLibraries>
    <AndroidStoreUncompressedFileExtensions>.so</AndroidStoreUncompressedFileExtensions>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" />
    <PackageReference Include="ZXing.Net" />
  </ItemGroup>

  <ItemGroup>
    <AndroidAsset Include="..\..\.tools\xray\26.3.27\windows-x64\geoip.dat" Link="geoip.dat" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiTunnel.App\DiTunnel.App.csproj" />
    <ProjectReference Include="..\DiTunnel.Platform.Android\DiTunnel.Platform.Android.csproj" />
  </ItemGroup>

</Project>
