<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Di-Tunnel.NetworkHost</AssemblyName>
    <Version>$(WindowsVersion)</Version>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../DiTunnel.Desktop/app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DiTunnel.Platform.Windows/DiTunnel.Platform.Windows.csproj" />
  </ItemGroup>
</Project>
