using System.Diagnostics;
using System.Net;
using System.Net.Sockets;

namespace DiTunnel.Infrastructure.Xray;

public static class XrayServerProbe
{
    public static async Task<double> MeasureAsync(XrayProfileConfiguration configuration, IPAddress address, string runtime, string path, CancellationToken cancellationToken, bool useHttps = true, string? outboundSourceAddress = null, bool tcpOnly = false, TimeSpan? probeTimeout = null)
    {
        using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        var budget = probeTimeout ?? TimeSpan.FromSeconds(12);
        timeout.CancelAfter(budget);
        var listener = new TcpListener(IPAddress.Loopback, 0);
        listener.Start();
        var port = ((IPEndPoint)listener.LocalEndpoint).Port;
        listener.Stop();
        var content = configuration.Build(address.ToString(), false, port, outboundSourceAddress: outboundSourceAddress, enableSocksUdp: false).Replace("\"loglevel\":\"none\"", "\"loglevel\":\"info\"");
        await File.WriteAllTextAsync(path, content, timeout.Token);
        // This configuration is generated by XrayProfileConverter. Avoid `xray run -test`
        // here because it starts the inbound on Windows, then races the real process for
        // the same local port and other short-lived resources.
        await using var manager = new XrayProcessManager(new XrayOptions
        {
            ExecutablePath = runtime,
            WorkingDirectory = Path.GetDirectoryName(runtime)!,
            ShutdownTimeout = TimeSpan.FromMilliseconds(250),
            ValidateConfigurationBeforeStart = false
        });
        var certificateError = 0;
        var listenerError = 0;
        manager.LogReceived += entry =>
        {
            if (entry.Message.Contains("x509:", StringComparison.OrdinalIgnoreCase) || entry.Message.Contains("failed to verify certificate", StringComparison.OrdinalIgnoreCase))
                Interlocked.Exchange(ref certificateError, 1);
            if (entry.Message.Contains("failed to listen", StringComparison.OrdinalIgnoreCase) || entry.Message.Contains("bind:", StringComparison.OrdinalIgnoreCase))
                Interlocked.Exchange(ref listenerError, 1);
        };
        try
        {
            await manager.StartAsync(path, timeout.Token);
            if (tcpOnly)
            {
                if (configuration.SupportsIpv4)
                    return await SocksTcpProbe.MeasureAsync(port, IPAddress.Parse("1.1.1.1"), 443, timeout.Token);
                return await SocksTcpProbe.MeasureAsync(port, IPAddress.Parse("2606:4700:4700::1111"), 443, timeout.Token,
                    new System.Net.Security.SslClientAuthenticationOptions { TargetHost = "one.one.one.one" });
            }
            using var handler = new HttpClientHandler { UseProxy = true, Proxy = new WebProxy($"socks5://127.0.0.1:{port}") };
            using var client = new HttpClient(handler);
            var watch = Stopwatch.StartNew();
            var target = useHttps ? configuration.SupportsIpv4 ? "https://1.1.1.1/cdn-cgi/trace" : "https://one.one.one.one/cdn-cgi/trace" : "http://cp.cloudflare.com/";
            using var request = new HttpRequestMessage(useHttps ? HttpMethod.Get : HttpMethod.Head, target);
            using var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, timeout.Token);
            response.EnsureSuccessStatusCode();
            return watch.Elapsed.TotalMilliseconds;
        }
        catch (InvalidOperationException) when (Volatile.Read(ref listenerError) != 0)
        {
            throw new InvalidOperationException("Xray не смог открыть локальный порт проверки. Повторите проверку.");
        }
        catch (HttpRequestException)
        {
            await manager.StopAsync(CancellationToken.None);
            if (Volatile.Read(ref certificateError) != 0)
                throw new InvalidOperationException("Сертификат VPN-сервера не прошёл проверку. Проверьте SNI и сертификат.");
            throw new InvalidOperationException("Сервер не ответил.");
        }
        catch (IOException) { throw new InvalidOperationException("Сервер не установил контрольное TCP-соединение через туннель."); }
        catch (System.Security.Authentication.AuthenticationException) { throw new InvalidOperationException("Не удалось подтвердить TLS-соединение с контрольным узлом через туннель."); }
        catch (OperationCanceledException) when (!cancellationToken.IsCancellationRequested)
        {
            throw new TimeoutException($"Проверка сервера превысила {budget.TotalSeconds:F0} секунд.");
        }
    }
}
