<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Version>$(WindowsVersion)</Version>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiTunnel.Core\DiTunnel.Core.csproj" />
    <PackageReference Include="Microsoft.Windows.CsWin32" PrivateAssets="all" />
  </ItemGroup>

<ItemGroup><ProjectReference Include="..\DiTunnel.Infrastructure.Xray\DiTunnel.Infrastructure.Xray.csproj" /></ItemGroup>
</Project>
