<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Di-Tunnel</AssemblyName>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Svg.Controls.Skia.Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiTunnel.App\DiTunnel.App.csproj" />
    <ProjectReference Include="..\DiTunnel.Infrastructure.Xray\DiTunnel.Infrastructure.Xray.csproj" />
    <ProjectReference Include="..\DiTunnel.Platform.Windows\DiTunnel.Platform.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\.tools\xray\26.3.27\windows-x64\geoip.dat" Link="Runtime\geoip.dat" CopyToOutputDirectory="PreserveNewest" Condition="Exists('..\..\.tools\xray\26.3.27\windows-x64\geoip.dat')" />
    <Content Include="..\..\.tools\xray\26.3.27\windows-x64\xray.exe" Link="Runtime\xray.exe" CopyToOutputDirectory="PreserveNewest" Condition="Exists('..\..\.tools\xray\26.3.27\windows-x64\xray.exe')" />
    <Content Include="..\..\.tools\xray\26.3.27\windows-x64\wintun.dll" Link="Runtime\wintun.dll" CopyToOutputDirectory="PreserveNewest" Condition="Exists('..\..\.tools\xray\26.3.27\windows-x64\wintun.dll')" />
    <Content Include="..\..\.tools\xray\26.3.27\windows-x64\LICENSE*" Link="Runtime\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
